apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: code-collab
data:
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "code_collab"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  JUDGE0_HOST: "judge0-api"
  JUDGE0_PORT: "2358"
  WEBHOOK_CALLBACK_URL: "http://webhook-handler:3000/webhook"
  CUSTOM_SUBMISSIONS_QUEUE_NAME: "custom:submissions:queue"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: judge0-config
  namespace: code-collab
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "judge0"
  AUTHN_HEADER: "X-Auth-Token"
  ENABLE_WAIT_RESULT: "true"
  MAX_QUEUE_SIZE: "100"
  CPU_TIME_LIMIT: "5"
  MAX_CPU_TIME_LIMIT: "15"
  ENABLE_CALLBACKS: "true" 