apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0-workers
  namespace: code-collab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: judge0-worker
  template:
    metadata:
      labels:
        app: judge0-worker
    spec:
      containers:
      - name: judge0-worker
        image: judge0/judge0:1.13.0
        command: ["/judge0-worker.sh"]
        envFrom:
        - configMapRef:
            name: app-config
        - configMapRef:
            name: judge0-config
        - secretRef:
            name: app-secrets
        - secretRef:
            name: judge0-secrets
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi" 